In [5]:
#Question 1:

import numpy as np
new_array=np.array([1,2,3,6,8,9])
num_list= new_array.tolist ()
print("The converted list is ",new_array)

La liste convertit est [1 2 3 6 8 9]


In [9]:
#Question 2:
import numpy as np
x = np.arange(9).reshape(3,3)
result = np.trace(x)
print("The sum of the diagonal elements are",result)

The sum of the diagonal elements are 12


In [11]:
#Question 3:
import numpy as np
y= np.array ([[1,2],[3,5]])
print("Values higher than y are ",y[y>=3] )

Values higher than y are  [3 5]


In [12]:
#Question 4:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
A=np.add(x,y)
print (A)

[[ 6.  8.]
 [10. 12.]]


In [15]:
#Question5:
import numpy as np
a= np.random.rand(3,4)
b= a-a.mean(axis=1, keepdims=True)
print(b)

[[ 0.07583864  0.41765368 -0.19955119 -0.29394113]
 [-0.10472062 -0.0524027  -0.21368826  0.37081158]
 [-0.06656563  0.52160166 -0.09668687 -0.35834916]]
